package View;

import model.Author;
import model.Book;
import model.Publisher;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author gabri
 */
public class Janela extends javax.swing.JFrame implements View{

    /**
     * Creates new form Viewgi
     */
    
    private DefaultTableModel tbModelAuthors;
    private DefaultTableModel tbModelPublishers;
    private DefaultTableModel tbModelBooks;
    
    public Janela(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable_Autor = new javax.swing.JTable();
        txt_SobrenomeAutorBusca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_NomeAutorBusca = new javax.swing.JTextField();
        btn_BuscarAutores = new javax.swing.JButton();
        btn_EditarAutor = new javax.swing.JButton();
        btn_ExcluirAutor = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_SobrenomeNovoAutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_NomeNovoAutor = new javax.swing.JTextField();
        btn_AddNovoAutor = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        table_Editoras = new javax.swing.JScrollPane();
        jtable_Editoras = new javax.swing.JTable();
        btn_EditarEditora = new javax.swing.JButton();
        btn_BuscarEditora = new javax.swing.JButton();
        btn_ExcluirEditora = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_NomeBuscaEditora = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txt_NomeEditora = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_SiteEditora = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btn_AddEditora = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        table_Livros = new javax.swing.JScrollPane();
        jtable_Livros = new javax.swing.JTable();
        txt_tituloLivroBuscar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_buscarLivro = new javax.swing.JButton();
        btn_editarLivro = new javax.swing.JButton();
        btn_excluirLivro = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_isbn = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_AutoresDoLivro = new javax.swing.JTextArea();
        cbo_autoresExistentes = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btn_addListaAutoresLivros = new javax.swing.JButton();
        cbo_EditorasExistentes = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_Preco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_removeListaAutoresLivros = new javax.swing.JButton();
        btn_AddNovoLivro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtable_Autor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Sobrenome"
            }
        ));
        jScrollPane2.setViewportView(jtable_Autor);

        txt_SobrenomeAutorBusca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Sobrenome:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nome:");

        txt_NomeAutorBusca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_BuscarAutores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_BuscarAutores.setText("Buscar");

        btn_EditarAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_EditarAutor.setText("Editar");

        btn_ExcluirAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_ExcluirAutor.setText("Excluir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_SobrenomeAutorBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txt_NomeAutorBusca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_EditarAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ExcluirAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_BuscarAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_SobrenomeAutorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btn_BuscarAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_NomeAutorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addComponent(btn_ExcluirAutor))
                            .addGap(34, 34, 34)
                            .addComponent(btn_EditarAutor)
                            .addGap(8, 8, 8))))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Listar Autores", jPanel2);

        txt_SobrenomeNovoAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Sobrenome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Nome:");

        txt_NomeNovoAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_AddNovoAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_AddNovoAutor.setText("Adicionar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_NomeNovoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(txt_SobrenomeNovoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addComponent(btn_AddNovoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NomeNovoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_SobrenomeNovoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_AddNovoAutor)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Adicionar", jPanel3);

        jTabbedPane1.addTab("Autores", jTabbedPane3);

        jtable_Editoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "URL"
            }
        ));
        table_Editoras.setViewportView(jtable_Editoras);

        btn_EditarEditora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_EditarEditora.setText("Editar");

        btn_BuscarEditora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_BuscarEditora.setText("Buscar");

        btn_ExcluirEditora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_ExcluirEditora.setText("Excluir");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Nome:");

        txt_NomeBuscaEditora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NomeBuscaEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeBuscaEditoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(table_Editoras, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_EditarEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_NomeBuscaEditora)
                                .addGap(50, 50, 50)
                                .addComponent(btn_ExcluirEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_BuscarEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(txt_NomeBuscaEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_ExcluirEditora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_EditarEditora)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_BuscarEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(table_Editoras, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Listar Editoras", jPanel5);

        txt_NomeEditora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Nome:");

        txt_SiteEditora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Site da Editora:");

        btn_AddEditora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_AddEditora.setText("Adicionar Editora");
        btn_AddEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddEditoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txt_NomeEditora)
                        .addGap(184, 184, 184))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel14))
                            .addComponent(jLabel15)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(txt_SiteEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_AddEditora)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(77, 77, 77))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SiteEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AddEditora))
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Adicionar", jPanel6);

        jTabbedPane1.addTab("Editoras", jTabbedPane4);

        jtable_Livros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Titulo", "Preço R$"
            }
        ));
        table_Livros.setViewportView(jtable_Livros);

        txt_tituloLivroBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Título do Livro:");

        btn_buscarLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_buscarLivro.setText("Buscar");

        btn_editarLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_editarLivro.setText("Editar");

        btn_excluirLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_excluirLivro.setText("Excluir");
        btn_excluirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(table_Livros, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_editarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tituloLivroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(btn_excluirLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tituloLivroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(btn_excluirLivro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_editarLivro)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(btn_buscarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(table_Livros, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Listar Livros", jPanel8);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("ISBN:");

        txt_isbn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isbnActionPerformed(evt);
            }
        });

        txt_titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Título:");

        txtArea_AutoresDoLivro.setEditable(false);
        txtArea_AutoresDoLivro.setColumns(20);
        txtArea_AutoresDoLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArea_AutoresDoLivro.setRows(5);
        jScrollPane1.setViewportView(txtArea_AutoresDoLivro);

        cbo_autoresExistentes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Autores do livro:");

        btn_addListaAutoresLivros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_addListaAutoresLivros.setText("Adicionar");

        cbo_EditorasExistentes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Preço R$:");

        txt_Preco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Editora:");

        btn_removeListaAutoresLivros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_removeListaAutoresLivros.setText("Remover");

        btn_AddNovoLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_AddNovoLivro.setText("Adicionar Novo Livro");
        btn_AddNovoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddNovoLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 105, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_EditorasExistentes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbo_autoresExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_addListaAutoresLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btn_removeListaAutoresLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btn_AddNovoLivro)
                        .addGap(16, 16, 16))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(43, 43, 43)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(49, 49, 49)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_autoresExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btn_addListaAutoresLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_removeListaAutoresLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbo_EditorasExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btn_AddNovoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Adicionar", jPanel9);

        jTabbedPane1.addTab("Livros", jTabbedPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddEditoraActionPerformed

    private void txt_NomeBuscaEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeBuscaEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeBuscaEditoraActionPerformed

    private void btn_AddNovoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddNovoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddNovoLivroActionPerformed

    private void btn_excluirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_excluirLivroActionPerformed

    private void txt_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddEditora;
    private javax.swing.JButton btn_AddNovoAutor;
    private javax.swing.JButton btn_AddNovoLivro;
    private javax.swing.JButton btn_BuscarAutores;
    private javax.swing.JButton btn_BuscarEditora;
    private javax.swing.JButton btn_EditarAutor;
    private javax.swing.JButton btn_EditarEditora;
    private javax.swing.JButton btn_ExcluirAutor;
    private javax.swing.JButton btn_ExcluirEditora;
    private javax.swing.JButton btn_addListaAutoresLivros;
    private javax.swing.JButton btn_buscarLivro;
    private javax.swing.JButton btn_editarLivro;
    private javax.swing.JButton btn_excluirLivro;
    private javax.swing.JButton btn_removeListaAutoresLivros;
    public javax.swing.JComboBox<Object> cbo_EditorasExistentes;
    public javax.swing.JComboBox<Object> cbo_autoresExistentes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jtable_Autor;
    private javax.swing.JTable jtable_Editoras;
    private javax.swing.JTable jtable_Livros;
    private javax.swing.JScrollPane table_Editoras;
    private javax.swing.JScrollPane table_Livros;
    private javax.swing.JTextArea txtArea_AutoresDoLivro;
    private javax.swing.JTextField txt_NomeAutorBusca;
    private javax.swing.JTextField txt_NomeBuscaEditora;
    private javax.swing.JTextField txt_NomeEditora;
    private javax.swing.JTextField txt_NomeNovoAutor;
    private javax.swing.JTextField txt_Preco;
    private javax.swing.JTextField txt_SiteEditora;
    private javax.swing.JTextField txt_SobrenomeAutorBusca;
    private javax.swing.JTextField txt_SobrenomeNovoAutor;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_titulo;
    private javax.swing.JTextField txt_tituloLivroBuscar;
    // End of variables declaration//GEN-END:variables

        private void refreshTableBooks(List<Book> books) {
        tbModelBooks.setRowCount(0);
        this.fillOutBooksComponents(books);
    }

    private void refreshTablePublisher(List<Publisher> publishers) {
        cbo_EditorasExistentes.removeAllItems();
        tbModelPublishers.setRowCount(0);

        this.fillOutPublisherComponents(publishers);
    }

    private void refreshTableAuthors(List<Author> authors) {
        cbo_autoresExistentes.removeAllItems();
        tbModelAuthors.setRowCount(0);

        this.fillOutAuthorsComponents(authors);
    }

    private void fillOutAuthorsComponents(List<Author> authors){
        tbModelAuthors = (DefaultTableModel) jtable_Autor.getModel();

        for(Author a : authors){
            String tbDataAuthors[] = {String.valueOf(a.getAuthor_id()), a.getFirstName(), a.getLastName()};
            tbModelAuthors.addRow(tbDataAuthors);

            cbo_autoresExistentes.addItem(a);
        }
    }

    private void fillOutPublisherComponents(List<Publisher> publishers){
        tbModelPublishers = (DefaultTableModel) jtable_Editoras.getModel();

        for(Publisher p : publishers){
            String tbDataPublishers[] = {String.valueOf(p.getPublisher_id()), p.getName(), p.getUrl()};
            tbModelPublishers.addRow(tbDataPublishers);

            cbo_EditorasExistentes.addItem(p);
        }
    }

    private void fillOutBooksComponents(List<Book> books){
        tbModelBooks = (DefaultTableModel) jtable_Livros.getModel();

        for(Book b : books){
            String tbDataBooks[] = {b.getIsbn(), b.getTitle(), String.valueOf(b.getPrice())};
            tbModelBooks.addRow(tbDataBooks);
        }
    }

    @Override
    public void initVisualComponents(List<Book> books, List<Publisher> publishers, List<Author> authors) {
        this.fillOutAuthorsComponents(authors);

        this.fillOutPublisherComponents(publishers);

        this.fillOutBooksComponents(books);
    }

    @Override
    public void refreshVisualComponents(List<Book> books, List<Publisher> publishers, List<Author> authors) {
        if(books != null && !books.isEmpty())
            this.refreshTableBooks(books);

        if(publishers != null && !publishers.isEmpty())
            this.refreshTablePublisher(publishers);

        if(authors != null && !authors.isEmpty())
            this.refreshTableAuthors(authors);
    }

    @Override
    public void addExistentAuthorsToListActionListner(ActionListener al) {
        btn_addListaAutoresLivros.addActionListener(al);
    }

    @Override
    public Author getEditAuthors() {
        if(jtable_Autor.getSelectionModel().isSelectionEmpty())
            return null;

        int Id = Integer.valueOf(jtable_Autor.getValueAt(jtable_Autor.getSelectedRow(), 0).toString());
        String actualFirstName = jtable_Autor.getValueAt(jtable_Autor.getSelectedRow(), 1).toString();
        String actualLastName = jtable_Autor.getValueAt(jtable_Autor.getSelectedRow(), 2).toString();

        String completeActualName = actualFirstName + " " + actualLastName;

        String refreshedFirstName = JOptionPane.showInputDialog("Deseja atualizar o nome do autor "+completeActualName+" ?");
        String refreshedLastName = JOptionPane.showInputDialog("Deseja atualizar o sobrenome do autor "+completeActualName+" ?");

        if(refreshedFirstName == null || refreshedFirstName.equals("") || refreshedFirstName.trim().equals(""))
            refreshedFirstName = actualFirstName;

        if(refreshedLastName == null || refreshedLastName.equals("") || refreshedLastName.trim().equals(""))
            refreshedLastName = actualLastName;

        return new Author(Id, refreshedLastName, refreshedFirstName);
    }

    @Override
    public int getDeleteAuthor() {
        if(jtable_Autor.getSelectionModel().isSelectionEmpty())
            return 0;
        
        int excludeBooksAndAuthors = JOptionPane.showConfirmDialog(null,"Deseja apagar o autor e todos os livros dele?");
        
        if(excludeBooksAndAuthors == 1)
            return 0 ;
        
        return Integer.parseInt(jtable_Autor.getValueAt(jtable_Autor.getSelectedRow(), 0).toString());
    }

    @Override
    public void addActionListnerAuthor(ActionListener al) {
        btn_AddNovoAutor.addActionListener(al);
    }

    @Override
    public void editActionListnerAuthor(ActionListener al) {
        btn_EditarAutor.addActionListener(al);
    }

    @Override
    public void excludeActionListnerAuthor(ActionListener al) {
        btn_ExcluirAutor.addActionListener(al);
    }

    @Override
    public Book getEditBooks() {
        if(jtable_Livros.getSelectionModel().isSelectionEmpty())
            return null;

        String isbn = jtable_Livros.getValueAt(jtable_Livros.getSelectedRow(), 0).toString();
        String actualBookTitle = jtable_Livros.getValueAt(jtable_Livros.getSelectedRow(), 1).toString();
        String actualBookPrice = jtable_Livros.getValueAt(jtable_Livros.getSelectedRow(), 2).toString();

        String refreshedBookTitle = JOptionPane.showInputDialog("Deseja atualizar o titulo do livro "+actualBookTitle+" ?");
        String refreshedBookPrice = JOptionPane.showInputDialog("Deseja atualizar o preço do livro "+actualBookTitle+" ?");

        if(refreshedBookTitle == null || refreshedBookTitle.equals("") || refreshedBookTitle.trim().equals(""))
            refreshedBookTitle = actualBookTitle;

        if(refreshedBookPrice == null || refreshedBookPrice.equals("") || refreshedBookPrice.trim().equals(""))
            refreshedBookPrice = actualBookPrice;

        double parsedValue = 0.0;
        try{
           parsedValue = Double.parseDouble(refreshedBookPrice);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Valor inserido inválido! o valor : "+ refreshedBookPrice +", não é válido e foi desconsiderado.");
            refreshedBookPrice = actualBookPrice;
        }

        return new Book(refreshedBookTitle, isbn, Double.parseDouble(refreshedBookPrice));
    }

    @Override
    public String getDeleteBook() {
        if(jtable_Livros.getSelectionModel().isSelectionEmpty())
            return "";

        return String.valueOf(jtable_Livros.getValueAt(jtable_Livros.getSelectedRow(), 0).toString());
    }

    @Override
    public void addActionListnerBook(ActionListener al) {
        btn_AddNovoLivro.addActionListener(al);
    }

    @Override
    public void editActionListnerBook(ActionListener al) {
        btn_editarLivro.addActionListener(al);
    }

    @Override
    public void excludeActionListnerBook(ActionListener al) {
        btn_excluirLivro.addActionListener(al);
    }

    @Override
    public Publisher getEditPublishers() {
        if(jtable_Editoras.getSelectionModel().isSelectionEmpty())
            return null;

        int Id = Integer.valueOf(jtable_Editoras.getValueAt(jtable_Editoras.getSelectedRow(), 0).toString());
        String actualName = jtable_Editoras.getValueAt(jtable_Editoras.getSelectedRow(), 1).toString();

        String publisherNameRefreshed = JOptionPane.showInputDialog("Deseja atualizar o nome da editora "+actualName+" ?");
        String publisherUrlRefreshed = JOptionPane.showInputDialog("Deseja atualizar a URL da editora "+actualName+" ?");

        if(publisherNameRefreshed == null || publisherNameRefreshed.equals("") || publisherNameRefreshed.trim().equals(""))
            publisherNameRefreshed = actualName;

        if(publisherUrlRefreshed == null || publisherUrlRefreshed.equals("") || publisherUrlRefreshed.trim().equals(""))
            publisherUrlRefreshed = jtable_Editoras.getValueAt(jtable_Editoras.getSelectedRow(), 2).toString();
        
        return new Publisher(Id, publisherNameRefreshed, publisherUrlRefreshed);
    }

    @Override
    public int getDeletePublishers() {
        if(jtable_Editoras.getSelectionModel().isSelectionEmpty())
            return 0;
        
        int excludeAllBooks = JOptionPane.showConfirmDialog(null,"Deseja apagar a editora e todos os livros dela?");
        
        System.out.println(excludeAllBooks);
        
        if(excludeAllBooks >= 1)
            return 0 ;
        
        return Integer.parseInt(jtable_Editoras.getValueAt(jtable_Editoras.getSelectedRow(), 0).toString());
    }

    @Override
    public void addActionListnerPublisher(ActionListener al) {
        btn_AddEditora.addActionListener(al);
    }

    @Override
    public void editActionListnerPublisher(ActionListener al) {
        btn_EditarEditora.addActionListener(al);
    }

    @Override
    public void excludeActionListnerPublisher(ActionListener al) {
        btn_ExcluirEditora.addActionListener(al);
    }

    @Override
    public Publisher getAddPublisher() {
        String publisherName = txt_NomeEditora.getText();
        String url = txt_SiteEditora.getText();
        int id = 1;

        return new Publisher(id, publisherName, url);
    }

    @Override
    public Author getAddAuthor() {
        String name = txt_NomeNovoAutor.getText();
        String fName = txt_SobrenomeNovoAutor.getText();

        return new Author(fName, name);
    }

    @Override
    public Author getAuthorSelected() {
        return (Author) cbo_autoresExistentes.getSelectedItem();
    }

    @Override
    public Author getSearchAuthors() {
        String name = txt_NomeAutorBusca.getText();
        String fName = txt_SobrenomeAutorBusca.getText();

        return new Author(fName, name);
    }

    @Override
    public Book getAddBook(List<Author> authors, Publisher publisher) {
       String titulo = "";
       String isbn = "";
       double price = 0;
        try {
            if(txt_titulo.getText().equals("") || txt_isbn.getText().equals("") || txt_Preco.getText().equals("")) {
                throw new Exception("Por favor preencha todos os campos!");
            } else {
                titulo = txt_titulo.getText();
                try {
                    isbn = String.valueOf(Integer.parseInt(txt_isbn.getText()));
                    price = Double.parseDouble(txt_Preco.getText());

                    if(price < 0)
                        throw new Exception("Valor inválido! (valor não pode ser negativo)");
                } catch (java.lang.NumberFormatException e) {
                    throw new Exception("ISBN inválido");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally{
            txt_titulo.setText("");
            txt_isbn.setText("");
            txt_Preco.setText("");
       }
       return new Book(titulo, isbn, authors, price, publisher.getPublisher_id());
    }

    @Override
    public String getSearchBooks() {
        return txt_tituloLivroBuscar.getText();
    }

    @Override
    public String getListPublishers() {
        return txt_NomeEditora.getText();
    }

    @Override
    public Publisher getPublisherSelected() {
        Publisher p = (Publisher) cbo_EditorasExistentes.getSelectedItem();
        System.out.println(p.getPublisher_id());
        return p;
    }

    @Override
    public void removeExistentAuthorsToListActionListner(ActionListener al) {
        btn_removeListaAutoresLivros.addActionListener(al);
    }

    @Override
    public void atualizaTextoListaAutores(List<Author> authors) {
        String refreshedText = "";
        if(!authors.isEmpty()){
            for(Author a : authors){
               refreshedText += a + "; ";
            }
            txtArea_AutoresDoLivro.setText(refreshedText);
            refreshedText = "";
        }
        else{
            txtArea_AutoresDoLivro.setText("");
        }
    }

    @Override
    public void searchActionListnerPublisher(ActionListener al) {
       btn_BuscarEditora.addActionListener(al);
    }

    @Override
    public String getSearchPublishers() {
        return txt_NomeBuscaEditora.getText();
    }

    @Override
    public void searchActionListnerAutor(ActionListener al) {
        btn_BuscarAutores.addActionListener(al);
    }

    @Override
    public void searchActionListnerBook(ActionListener al) {
       btn_buscarLivro.addActionListener(al);
    }
}